"""Core state definitions for MCGS workflow."""

from typing import Any, Dict, List, Optional, Annotated
from typing_extensions import NotRequired, TypedDict
import operator

from m3os.agents_v5.tools.monte_carlo_graph.graph_for_molecular_optimization_v3_4 import MolecularGraph


class MCGSState(TypedDict):
    """Workflow state definition for Monte Carlo Graph Search molecular optimization.
    
    This TypedDict defines the complete state that flows through the LangGraph workflow.
    Fields are organized by their purpose in the optimization pipeline.
    """
    
    # ==================== Initial Information ====================
    initial_smiles: str
    """The SMILES string of the initial molecule to be optimized."""
    
    initial_iupac: str
    """The IUPAC name of the initial molecule."""
    
    initial_fragments: str
    """Functional groups/fragments identified in the initial molecule."""
    
    optimization_goal: str
    """The optimization objective (e.g., 'reduce CYP2C8 inhibition')."""

    project_manager_brief: str
    """Natural-language task brief prepared by the main agent for the MCGS team."""

    selected_admet_properties: List[str]
    """Task-level frozen ADMET endpoints selected before MCGS expansion."""

    selected_admet_preference_json: str
    """Canonical JSON object mapping frozen ADMET endpoints to higher/lower directions."""

    selected_admet_property_details: List[Dict[str, Any]]
    """Metadata and rationale for each selected ADMET endpoint."""

    selected_admet_property_rationale: str
    """Explanation for the task-level ADMET endpoint selection."""

    selected_admet_task_signature: str
    """Stable signature of the optimization task used to select the ADMET endpoints."""
    
    # ==================== Shared Context & Intermediate Results ====================
    current_shared_analysis: Dict[str, Any]
    """Structured shared analysis for the current molecule, reused by all agents."""

    shared_analysis_cache: Dict[str, Dict[str, Any]]
    """Cache keyed by canonical SMILES to avoid repeated analysis on same node."""

    molecule_facts_cache: Dict[str, Dict[str, Any]]
    """Canonical-SMILES keyed cache for reusable molecule facts such as IUPAC and fragments."""

    agent_memory: Dict[str, List[Dict[str, Any]]]
    """Auditor-extracted role memory for rational, creative, and critic agents."""

    screening_context_history: Annotated[List[Dict[str, Any]], operator.add]
    """Accumulated Mol2Mol screening evidence shared with both generator roles."""
    
    current_info_list: Annotated[List[Dict[str, Any]], operator.add]
    """List tracking the optimization path through the graph.
    
    Each element is a dictionary containing:
    - current_smiles: SMILES of the molecule at this step
    - current_iupac: IUPAC name
    - current_fragments: Functional groups
    - current_selection_context: concise context for why this node was selected
    - current_select_reason: Reason for selecting this molecule
    """
    
    # ==================== Evaluation & Candidates ====================
    optimized_molecules: List[Dict[str, Any]]
    """Combined list of optimized molecules from both agents.
    
    Each molecule dict contains:
    - SMILES: The molecule SMILES
    - modification_type: Type of modification made
    - rationale: Explanation for the modification
    - confidence_score: Agent's confidence in this modification
    - agent_type: 'creative_molecule_explorer' or 'rational_medicinal_designer'
    """
    
    optimized_molecules_creative: List[Dict[str, Any]]
    """Molecules generated by the Creative Molecule Explorer."""
    
    optimized_molecules_rational: List[Dict[str, Any]]
    """Molecules generated by the Rational Medicinal Designer."""

    creative_agent_traces: Annotated[List[Dict[str, Any]], operator.add]
    """Full per-round traces for the creative agent, including tool calls/messages."""

    rational_agent_traces: Annotated[List[Dict[str, Any]], operator.add]
    """Full per-round traces for the rational agent, including tool calls/messages."""

    subagent_trace_rounds: Annotated[List[Dict[str, Any]], operator.add]
    """Round-grouped creative/rational traces for easier downstream inspection."""
    
    critic_evaluation: str
    """Critic's evaluation results for the optimized molecules."""

    critic_auditor_evaluations: Annotated[List[Dict[str, Any]], operator.add]
    """Per-round structured Critic Auditor outputs used for final candidate reporting."""

    optimization_report_html: Optional[str]
    """Latest generated HTML optimization report content, if requested."""

    optimization_report_path: Optional[str]
    """Filesystem path for the latest generated optimization report, if requested."""
    
    # ==================== Flow Control ====================
    is_finished: bool
    """Flag indicating whether the optimization should terminate."""
    
    node_num_needed: int
    """Target number of optimized candidate molecules requested by the user.

    The MCGS graph also contains the root/input molecule, so graph-node based
    termination should compare against node_num_needed + 1.
    """

    iteration_num_needed: Optional[int]
    """Target number of MCGS expansion rounds requested by the user, when specified."""

    iteration_num_defaulted: NotRequired[bool]
    """Whether iteration_num_needed was filled from the no-count/no-round default."""

    current_mcgs_round: NotRequired[Optional[int]]
    """The active MCGS expansion round used for user-facing sub-agent events."""

    run_candidate_baseline: int
    """Number of valid non-root candidate molecules present when the current search run started."""

    run_target_candidate_count: int
    """Requested number of new valid candidate molecules for the current search run."""

    run_fixed_base_smiles: Optional[str]
    """User-specified base molecule SMILES for the current search run, when provided."""
    
    user_prompt: str
    """The original user prompt/input for the optimization task."""
    
    additional_context: Optional[str]
    """User-provided context prepended to every agent's system prompt."""

    runtime_metrics: Annotated[List[Dict[str, Any]], operator.add]
    """Per-step runtime/token metrics for observability."""
    
    mcgs_graph: MolecularGraph
    """The molecular graph tracking the MCGS exploration."""
    
    # ==================== Protein Information ====================
    initial_protein_squence: Optional[str]
    """Protein sequence for structure-based optimization (optional)."""

    protein_fasta_path: NotRequired[Optional[str]]
    """Authoritative FASTA path used by protein-aware prediction tools."""

    leadopt_task_contract: NotRequired[Dict[str, Any]]
    """Structured objectives, holds, baselines, and runtime constraints."""
