"""Runtime prompt templates for workflow and agent user turns."""

from .creative_user import USER_PROMPTS as CREATIVE_EXPLORER_USER_PROMPT
from .rational_user import USER_PROMPTS as RATIONAL_DESIGNER_USER_PROMPT
from .critic_user import USER_PROMPTS as CRITIC_USER_PROMPT
from .workflow import (
    EXTRACT_INFO_SYSTEM_PROMPT,
    INITIAL_ANALYZE_SYSTEM_PROMPT,
    INITIAL_ANALYZE_USER_PROMPT,
    SELECT_CANDIDATE_SYSTEM_PROMPT,
    SELECT_CANDIDATE_USER_PROMPT,
)

__all__ = [
    "CREATIVE_EXPLORER_USER_PROMPT",
    "RATIONAL_DESIGNER_USER_PROMPT",
    "CRITIC_USER_PROMPT",
    "EXTRACT_INFO_SYSTEM_PROMPT",
    "INITIAL_ANALYZE_SYSTEM_PROMPT",
    "INITIAL_ANALYZE_USER_PROMPT",
    "SELECT_CANDIDATE_SYSTEM_PROMPT",
    "SELECT_CANDIDATE_USER_PROMPT",
]
