"""Node: Evaluate and Update

This node evaluates the optimized molecules using the Critic agent,
updates the MCGS graph, and performs backpropagation.
"""

from typing import Any, Dict, List
import time

from m3os.agents_v5.core.state import MCGSState
from m3os.agents_v5.core.config import AgentConfig
from m3os.agents_v5.core.trace_utils import (
    safe_serialize,
    structured_field,
    structured_optimizations,
)
from m3os.agents_v5.services.admet_property_selection import (
    build_selected_admet_prompt_block,
)
from m3os.agents_v5.services.molecule_visual_context import (
    build_pair_difference_visual_context,
    build_topology_visual_context,
    contexts_to_metadata,
    text_block,
)
from m3os.agents_v5.services.molecular_context import (
    without_explicit_molecular_auxiliary_fields,
)
from m3os.agents_v5.agents.critic import CriticAgent
from m3os.agents_v5.prompts import CRITIC_USER_PROMPT
from m3os.agents_v5.tools.mcgs_tools import (
    mcgs_add_optimized_molecules,
    mcgs_backpropagate,
)
from m3os.agents_v5.workflow.audit_recovery import audit_with_empty_result_recovery
from m3os.agents_v5.services.smiles_validation import (
    compact_invalid_molecules,
    split_valid_molecules,
    tanimoto_similarity_to_root,
    validate_smiles,
)
from m3os.agents_v5.workflow.memory import (
    append_agent_memory,
    critic_feedback_items,
    critic_memory_items,
    format_agent_memory,
)


CRITIC_SCORE_WEIGHT = 0.8
ROOT_SIMILARITY_WEIGHT = 0.2
GENERATOR_AGENT_TYPES = {
    "creative_molecule_explorer",
    "rational_medicinal_designer",
}


class EvaluateAndUpdateNode:
    """Node for evaluating molecules and updating the graph.
    
    This node:
    1. Invokes the Critic agent to evaluate optimized molecules
    2. Adds evaluated molecules to the graph
    3. Performs backpropagation with the best score
    4. Visualizes the updated graph
    """
    
    def __init__(
        self,
        config: AgentConfig,
        critic_agent: CriticAgent,
        auditor_agent: Any = None,
    ):
        """Initialize the node.
        
        Args:
            config: Agent configuration
            critic_agent: Pre-configured critic agent instance
        """
        self.config = config
        self.critic_agent = critic_agent
        self.auditor_agent = auditor_agent
    
    async def __call__(self, state: MCGSState) -> Dict[str, Any]:
        """Execute the node.
        
        Args:
            state: Current workflow state
            
        Returns:
            Dictionary of updates to the state
        """
        print("\n=== Node: evaluate_and_update ===")
        start = time.perf_counter()
        
        # Get current molecular info
        current_info = state["current_info_list"][-1] if state["current_info_list"] else {}
        optimized_molecules = state.get("optimized_molecules") or []
        prior_invalid = state.get("invalid_molecules") if isinstance(state.get("invalid_molecules"), list) else []
        if not optimized_molecules:
            if prior_invalid:
                error = "All generated molecules were invalid or duplicate SMILES after RDKit validation."
            else:
                error = "No optimized molecules were generated by creative or rational agents."
            print(f"Skipping critic evaluation: {error}")
            return {
                "critic_evaluation": [],
                "expansion_error": error,
                "invalid_molecules_filtered": len(prior_invalid),
                "invalid_molecules": compact_invalid_molecules(prior_invalid),
                "runtime_metrics": [
                    {
                        "node": "evaluate_and_update",
                        "elapsed_sec": round(time.perf_counter() - start, 3),
                        "skipped": True,
                        "error": error,
                        "invalid_molecules_filtered": len(prior_invalid),
                    }
                ],
            }
        optimized_molecules, invalid_generated = split_valid_molecules(optimized_molecules)
        if not optimized_molecules:
            error = "All generated molecules were invalid or duplicate SMILES after RDKit validation."
            print(f"Skipping critic evaluation: {error}")
            return {
                "optimized_molecules": [],
                "critic_evaluation": [],
                "expansion_error": error,
                "invalid_molecules_filtered": len(prior_invalid) + len(invalid_generated),
                "invalid_molecules": compact_invalid_molecules(prior_invalid + invalid_generated),
                "runtime_metrics": [
                    {
                        "node": "evaluate_and_update",
                        "elapsed_sec": round(time.perf_counter() - start, 3),
                        "skipped": True,
                        "error": error,
                        "invalid_molecules_filtered": len(prior_invalid) + len(invalid_generated),
                    }
                ],
            }
        
        # Evaluate molecules with Critic
        round_index = len(state.get("current_info_list") or [])
        mcgs_round = state.get("current_mcgs_round") or round_index
        display_round = max(1, int(mcgs_round or 1))
        if hasattr(self.critic_agent, "set_event_context"):
            self.critic_agent.set_event_context(
                agent_type="critic",
                round=display_round,
                display_round=display_round,
                round_index=round_index,
                mcgs_round=display_round,
                display_mcgs_round=display_round,
                selected_admet_preference_json=state.get("selected_admet_preference_json"),
                selected_admet_properties=state.get("selected_admet_properties"),
                selected_admet_property_details=state.get("selected_admet_property_details"),
                initial_protein_sequence=state.get("initial_protein_squence"),
                protein_fasta_path=state.get("protein_fasta_path"),
                initial_smiles=state.get("initial_smiles"),
                current_smiles=current_info.get("current_smiles"),
                leadopt_task_contract=state.get("leadopt_task_contract"),
            )
        state_for_evaluation = {**state, "optimized_molecules": optimized_molecules}
        try:
            evaluation = await self._evaluate_molecules(state_for_evaluation, current_info)
        except Exception as exc:
            error = f"Critic evaluation failed: {type(exc).__name__}: {exc}"
            print(f"Skipping graph update: {error}")
            return {
                "critic_evaluation": [],
                "expansion_error": error,
                "invalid_molecules_filtered": len(prior_invalid) + len(invalid_generated),
                "invalid_molecules": compact_invalid_molecules(prior_invalid + invalid_generated),
                "runtime_metrics": [
                    {
                        "node": "evaluate_and_update",
                        "elapsed_sec": round(time.perf_counter() - start, 3),
                        "skipped": True,
                        "error": error,
                        "invalid_molecules_filtered": len(prior_invalid) + len(invalid_generated),
                    }
                ],
            }
        
        # Process evaluation results
        evaluation_res = self._process_evaluation(evaluation, optimized_molecules, state.get("initial_smiles"))
        evaluation_res, invalid_evaluated = split_valid_molecules(evaluation_res)
        invalid_molecules = prior_invalid + invalid_generated + invalid_evaluated
        if not evaluation_res:
            error = "Critic returned no valid molecule evaluations after RDKit validation."
            print(f"Skipping graph update: {error}")
            return {
                "critic_evaluation": [],
                "critic_auditor_evaluations": [self._critic_auditor_trace(evaluation, round_index)],
                "expansion_error": error,
                "invalid_molecules_filtered": len(invalid_molecules),
                "invalid_molecules": compact_invalid_molecules(invalid_molecules),
                "runtime_metrics": [
                    {
                        "node": "evaluate_and_update",
                        "elapsed_sec": round(time.perf_counter() - start, 3),
                        "skipped": True,
                        "error": error,
                        "invalid_molecules_filtered": len(invalid_molecules),
                        "audit_warnings": evaluation.get("audit_warnings") if isinstance(evaluation, dict) else None,
                        "auditor_trace": evaluation.get("auditor_trace") if isinstance(evaluation, dict) else None,
                        "audit_recovery_trace": evaluation.get("audit_recovery_trace") if isinstance(evaluation, dict) else None,
                    }
                ],
            }
        print("evaluation_res:", evaluation_res)
        agent_memory = self._updated_agent_memory(
            state.get("agent_memory"),
            evaluation_res,
            round_index,
        )
        
        # Get the molecular graph
        mol_graph = state["mcgs_graph"]
        
        # Add optimized molecules to graph
        mol_graph = mcgs_add_optimized_molecules(
            mol_graph=mol_graph,
            parent_node_smiles=current_info.get("current_smiles"),
            new_molecules_json=evaluation_res,
            parent_node_select_reason=current_info.get("current_select_reason"),
        )
        
        # Find highest scoring molecule using the MCGS selection score.
        highest_score_smiles = self._get_highest_score_smiles(evaluation_res)
        
        # Backpropagate
        mol_graph = mcgs_backpropagate(
            mol_graph=mol_graph,
            new_molecules_json=evaluation_res,
            selected_node_smiles=highest_score_smiles,
        )
        
        print("\n===[END] Node: evaluate_and_update ===")
        
        return {
            "mcgs_graph": mol_graph,
            "critic_evaluation": evaluation_res,
            "critic_auditor_evaluations": [self._critic_auditor_trace(evaluation, round_index)],
            "agent_memory": agent_memory,
            "invalid_molecules_filtered": len(invalid_molecules),
            "invalid_molecules": compact_invalid_molecules(invalid_molecules),
            "runtime_metrics": [
                {
                    "node": "evaluate_and_update",
                    "elapsed_sec": round(time.perf_counter() - start, 3),
                    "llm_usage": evaluation.get("llm_usage") if isinstance(evaluation, dict) else None,
                    "visual_contexts": evaluation.get("visual_contexts") if isinstance(evaluation, dict) else None,
                    "invalid_molecules_filtered": len(invalid_molecules),
                    "raw_agent_response": evaluation.get("raw_agent_response") if isinstance(evaluation, dict) else None,
                    "smiles_validation_gate": evaluation.get("smiles_validation_gate") if isinstance(evaluation, dict) else None,
                    "audit_warnings": evaluation.get("audit_warnings") if isinstance(evaluation, dict) else None,
                    "auditor_trace": evaluation.get("auditor_trace") if isinstance(evaluation, dict) else None,
                    "audit_recovery_trace": evaluation.get("audit_recovery_trace") if isinstance(evaluation, dict) else None,
                }
            ],
        }
    
    async def _evaluate_molecules(
        self,
        state: MCGSState,
        current_info: Dict[str, Any]
    ) -> Any:
        """Evaluate optimized molecules using the Critic agent.
        
        Args:
            state: Current workflow state
            current_info: Current molecular information
            
        Returns:
            Critic evaluation result
        """
        # Format the user prompt
        shared = state.get("current_shared_analysis") or {}
        query = CRITIC_USER_PROMPT.format(
            initial_smiles=state["initial_smiles"],
            initial_iupac=state["initial_iupac"],
            initial_fragments=state["initial_fragments"],
            optimization_goal=state["optimization_goal"],
            current_smiles=current_info.get("current_smiles"),
            current_iupac=current_info.get("current_iupac"),
            current_fragments=current_info.get("current_fragments"),
            optimized_molecules=str(state["optimized_molecules"]),
            project_manager_brief=state.get("project_manager_brief", ""),
            current_selection_context=current_info.get("current_selection_context"),
            initial_protein_squence=state.get("initial_protein_squence"),
            shared_analysis_summary=shared.get("shared_analysis_summary", ""),
            shared_keep_fragments=shared.get("shared_keep_fragments", []),
            shared_modifiable_fragments=shared.get("shared_modifiable_fragments", []),
            shared_risk_alerts=shared.get("shared_risk_alerts", []),
            shared_priority_directions=shared.get("shared_priority_directions", []),
            agent_memory=format_agent_memory(state.get("agent_memory"), "critic"),
        )
        if not self.config.enable_molecular_auxiliary_context:
            query = without_explicit_molecular_auxiliary_fields(query)
        query += build_selected_admet_prompt_block(state)

        visual_contexts = []
        visual_invocation_failed = False
        if not self.config.enable_molecular_auxiliary_context:
            result = await self.critic_agent.invoke(query)
        else:
            current_visual = build_topology_visual_context(
                smiles=current_info.get("current_smiles"),
                visual_id="CURRENT_PARENT",
                label="current parent molecule for Critic evaluation",
                iupac=current_info.get("current_iupac"),
                fragments=current_info.get("current_fragments"),
                image_prefix="critic_current_parent_topology",
            )
            visual_contexts.append(current_visual)
            candidate_blocks: List[Dict[str, Any]] = []
            for index, item in enumerate(state["optimized_molecules"], start=1):
                candidate_smiles = self._action_smiles(item)
                visual_id = f"CANDIDATE_{index:03d}"
                candidate_source = item.get("agent_type") if isinstance(item, dict) else ""
                context = build_pair_difference_visual_context(
                    parent_smiles=current_info.get("current_smiles"),
                    candidate_smiles=candidate_smiles,
                    visual_id=visual_id,
                    candidate_source_agent_type=candidate_source,
                    image_prefix=f"critic_{visual_id.lower()}_pair_difference",
                )
                visual_contexts.append(context)
                candidate_blocks.extend(context.content_blocks)

            visual_rules = (
                "[CRITIC VISUAL ALIGNMENT RULES]\n"
                "You are receiving 2D molecule visual context in addition to SMILES/IUPAC/fragments.\n"
                "For each candidate, align observations by Visual ID and Candidate SMILES exactly.\n"
                "Do not attribute a visual difference from one candidate image to another candidate.\n"
                "If a candidate visual context says the image is unavailable, evaluate that candidate from SMILES/IUPAC/metadata only and mention the missing visual if relevant.\n"
                "For pair difference images: Left = current parent, Right = candidate; green/shared MCS, orange/changed region, purple/stereochemistry change."
            )
            visual_query = [
                {
                    "role": "user",
                    "content": [
                        text_block(f"{query}\n\n{visual_rules}"),
                        *current_visual.content_blocks,
                        *candidate_blocks,
                    ],
                }
            ]

            try:
                result = await self.critic_agent.invoke(visual_query)
            except Exception as exc:
                visual_invocation_failed = True
                print(
                    "[Critic] Visual-context invocation failed; retrying text-only "
                    f"fallback: {type(exc).__name__}: {exc}"
                )
                for context in visual_contexts:
                    context.metadata["included_in_model_call"] = False
                    context.metadata.setdefault(
                        "visual_context_error",
                        f"visual invocation failed: {type(exc).__name__}: {exc}",
                    )
                result = await self.critic_agent.invoke(
                    f"{query}\n\n[VISUAL CONTEXT FALLBACK]\n"
                    "Molecule images were unavailable to the model for this Critic call; "
                    "evaluate all candidates using SMILES/IUPAC/fragments and generator metadata."
                )
        visual_metadata = contexts_to_metadata(visual_contexts)
        if isinstance(result, dict) and result.get("structured_response") is not None:
            result = dict(result)
            result["visual_contexts"] = visual_metadata
            if visual_invocation_failed:
                result["visual_context_fallback"] = True
            return result
        if self.auditor_agent is None:
            raise ValueError("Critic returned free-form output but no Auditor agent is configured.")
        audit_result = await audit_with_empty_result_recovery(
            agent=self.critic_agent,
            auditor_agent=self.auditor_agent,
            result=result,
            audit_kind="critic_evaluations",
            source_agent_type="critic",
            audit_method_name="audit_critic_evaluations",
            rerun_query=query,
        )
        if audit_result.get("audit_warnings"):
            print("[Critic Auditor warnings]:", safe_serialize(audit_result["audit_warnings"]))
        source_agent_result = (
            audit_result.get("source_agent_result")
            if isinstance(audit_result.get("source_agent_result"), dict)
            else result
        )
        return {
            "structured_response": audit_result["structured_response"],
            "raw_agent_response": audit_result.get("audit_source_text", ""),
            "original_agent_response": (
                source_agent_result.get("raw_response_text")
                if isinstance(source_agent_result, dict)
                else None
            ),
            "smiles_validation_gate": audit_result.get("smiles_validation_gate"),
            "auditor_trace": audit_result.get("auditor_trace"),
            "audit_finalization_trace": audit_result.get("audit_finalization_trace"),
            "audit_recovery_trace": audit_result.get("audit_recovery_trace"),
            "audit_warnings": audit_result.get("audit_warnings", []),
            "visual_contexts": visual_metadata,
            "visual_context_fallback": visual_invocation_failed,
            "llm_usage": {
                "agent": (
                    source_agent_result.get("llm_usage")
                    if isinstance(source_agent_result, dict)
                    else None
                ),
                "finalizer": audit_result.get("finalization_llm_usage"),
                "auditor": audit_result.get("llm_usage"),
            },
        }

    @staticmethod
    def _action_smiles(item: Any) -> str:
        if isinstance(item, dict):
            return str(item.get("smiles") or item.get("SMILES") or "").strip()
        return str(item or "").strip()
    
    def _process_evaluation(
        self,
        evaluation: Any,
        action_molecules: List[Dict[str, Any]],
        initial_smiles: Any = None,
    ) -> List[Dict[str, Any]]:
        """Process Critic evaluation and merge with generator info.
        
        Args:
            evaluation: Critic evaluation result
            action_molecules: Original molecules from generator agents
            
        Returns:
            List of processed molecule dictionaries
        """
        structured = evaluation.get("structured_response") if isinstance(evaluation, dict) else evaluation
        eval_list = self._extract_optimizations(structured)
        if not eval_list:
            return []
        processed = []
        
        for eval_res in eval_list:
            smiles = self._eval_field(eval_res, "smiles")
            if not smiles:
                continue
            # Find matching generator molecule; generator metadata is the
            # authoritative source for provenance fields such as agent_type.
            matching_action = self._find_matching_action(smiles, action_molecules)
            
            try:
                critic_score = float(self._eval_field(eval_res, "score", 0.0))
            except (TypeError, ValueError):
                critic_score = 0.0
            root_similarity = tanimoto_similarity_to_root(smiles, initial_smiles)
            similarity_for_score = root_similarity if root_similarity is not None else 0.0
            mcgs_selection_score = (
                CRITIC_SCORE_WEIGHT * critic_score
                + ROOT_SIMILARITY_WEIGHT * similarity_for_score
            )
            raw_properties = self._eval_field(eval_res, "properties", {})
            properties = dict(raw_properties) if isinstance(raw_properties, dict) else {}
            properties.setdefault("critic_score", critic_score)
            if root_similarity is not None:
                properties.setdefault("root_similarity", root_similarity)
            properties.setdefault("mcgs_selection_score", round(mcgs_selection_score, 4))

            processed.append({
                "smiles": smiles,
                "action": self._eval_field(eval_res, "action", ""),
                "critic_rationale": self._eval_field(eval_res, "rationale", ""),
                "generator_rationale": matching_action.get("rationale", "None") if matching_action else "None",
                "generator_confidence_score": float(matching_action.get("confidence_score", 0.0)) if matching_action else 0.0,
                "score": round(mcgs_selection_score, 4),
                "critic_score": critic_score,
                "root_similarity": root_similarity,
                "mcgs_selection_score": round(mcgs_selection_score, 4),
                "properties": properties,
                "agent_type": self._generator_agent_type(matching_action, eval_res),
            })
        
        return processed

    @staticmethod
    def _extract_optimizations(structured: Any) -> List[Any]:
        return structured_optimizations(structured)

    @staticmethod
    def _eval_field(eval_res: Any, field: str, default: Any = None) -> Any:
        return structured_field(eval_res, field, default)

    @classmethod
    def _find_matching_action(
        cls,
        smiles: str,
        action_molecules: List[Dict[str, Any]],
    ) -> Dict[str, Any] | None:
        for action in action_molecules:
            if not isinstance(action, dict):
                continue
            action_smiles = str(action.get("SMILES") or action.get("smiles") or "").strip()
            if action_smiles == smiles:
                return action

        ok, canonical, _error = validate_smiles(smiles)
        if not ok or not canonical:
            return None
        for action in action_molecules:
            if not isinstance(action, dict):
                continue
            action_canonical = str(action.get("canonical_smiles") or "").strip()
            if action_canonical and action_canonical == canonical:
                return action
        return None

    @classmethod
    def _generator_agent_type(
        cls,
        matching_action: Dict[str, Any] | None,
        eval_res: Any,
    ) -> str:
        if matching_action:
            agent_type = str(matching_action.get("agent_type") or "").strip()
            if agent_type:
                return agent_type

        # Backward-compatible fallback for legacy critic outputs that already
        # carried generator provenance. Never use "critic" as molecule source.
        critic_agent_type = str(cls._eval_field(eval_res, "agent_type", "") or "").strip()
        if critic_agent_type in GENERATOR_AGENT_TYPES:
            return critic_agent_type
        return ""

    def _critic_auditor_trace(self, evaluation: Any, round_index: int) -> Dict[str, Any]:
        evaluation_dict = evaluation if isinstance(evaluation, dict) else {}
        structured = evaluation_dict.get("structured_response") if evaluation_dict else evaluation
        optimizations = self._extract_optimizations(structured)
        return {
            "round_index": round_index,
            "display_round": max(1, round_index),
            "structured_response": safe_serialize(structured),
            "optimizations": safe_serialize(optimizations),
            "raw_agent_response": evaluation_dict.get("raw_agent_response"),
            "smiles_validation_gate": evaluation_dict.get("smiles_validation_gate"),
            "auditor_trace": evaluation_dict.get("auditor_trace"),
            "audit_recovery_trace": evaluation_dict.get("audit_recovery_trace"),
            "audit_warnings": evaluation_dict.get("audit_warnings", []),
            "visual_contexts": safe_serialize(evaluation_dict.get("visual_contexts")),
            "visual_context_fallback": evaluation_dict.get("visual_context_fallback"),
        }
    
    def _get_highest_score_smiles(self, molecules: List[Dict[str, Any]]) -> str:
        """Find the SMILES of the highest scoring molecule.
        
        Args:
            molecules: List of molecule dictionaries with scores
            
        Returns:
            SMILES string of highest scoring molecule
        """
        return max(molecules, key=lambda x: x.get("mcgs_selection_score", x["score"]))["smiles"]

    def _updated_agent_memory(
        self,
        memory: Any,
        evaluation_res: List[Dict[str, Any]],
        round_index: Any,
    ) -> Dict[str, List[Dict[str, Any]]]:
        updated = append_agent_memory(
            memory,
            "critic",
            critic_memory_items(evaluation_res, round_index=round_index),
        )
        updated = append_agent_memory(
            updated,
            "rational",
            critic_feedback_items(
                evaluation_res,
                round_index=round_index,
                agent_type="rational_medicinal_designer",
            ),
        )
        updated = append_agent_memory(
            updated,
            "creative",
            critic_feedback_items(
                evaluation_res,
                round_index=round_index,
                agent_type="creative_molecule_explorer",
            ),
        )
        return updated
